export default{
    termekek:[
        {
            _id:'1',
            nev:'Kényelmes Futó Cipő',
            kategoria: 'Cipok',
            kep:'../images/termek-1.jpg',
            ar:20000,
            marka:'Nike',
            ertekeles:4.2,
            ertekelesSzama:10,
            arukeszlet: 9,
        },
        {
            _id:'2',
            nev:'JBL Fejhallgató',
            kategoria: 'Fejhallgato',
            kep:'../images/termek-2.jpg',
            ar:35499,
            marka:'JBL',
            ertekeles:3.9,
            ertekelesSzama:8,
            arukeszlet: 2,
        },
        {
            _id:'3',
            nev:'UV Védő Napszemüveg',
            kategoria: 'Kiegesztiok',
            kep:'../images/termek-3.jpg',
            ar:10000,
            marka:'UVGlass',
            ertekeles:4.6,
            ertekelesSzama:17,
            arukeszlet: 4,
        },
        {
            _id:'4',
            nev:'Retro Polaroid Kamera',
            kategoria: 'Kamerak',
            kep:'../images/termek-4.jpg',
            ar:24999,
            marka:'Polaroid',
            ertekeles:4.2,
            ertekelesSzama:10,
            arukeszlet: 9,
        },
        {
            _id:'5',
            nev:'Stapabíró Hátizsák Túrázáshoz',
            kategoria: 'Kiegesztiok',
            kep:'../images/termek-5.jpg',
            ar:20000,
            marka:'Vinta',
            ertekeles:4.8,
            ertekelesSzama:31,
            arukeszlet: 1,
        },
    ],
};
